In [1]:
import numpy as np

In [4]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# 2D array
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)


[1 2 3 4]
[[1 2]
 [3 4]]


In [6]:
# Array of zeros
zeros = np.zeros((2, 3))  # 2x3 matrix of zeros

# Array of ones
ones = np.ones((3, 3))  # 3x3 matrix of ones

# Array with a range of values
arange = np.arange(1, 10, 2)  # Start: 1, Stop: 10, Step: 2

# Linearly spaced values
linspace = np.linspace(0, 1, 5)  # 5 equally spaced values between 0 and 1

print(zeros,ones,arange,linspace)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [1 3 5 7 9] [0.   0.25 0.5  0.75 1.  ]


In [7]:
print(type(zeros))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# Random values
random = np.random.rand(3, 3)  # 3x3 matrix of random values (0 to 1)

# Random integers
randint = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 10
print(randint)
random

[[1 2 3]
 [9 7 3]
 [3 7 8]]


array([[0.98805164, 0.9639512 , 0.51377808],
       [0.16725899, 0.57879808, 0.48699094],
       [0.3616004 , 0.33013809, 0.93419144]])

In [11]:
arr = np.array([1, 2, 3, 4, 5])

# Min, max, sum, mean, standard deviation
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))


1
5
15
3.0
1.4142135623730951


In [12]:
arr = np.arange(1, 10)

# Reshape to 3x3 matrix
reshaped = arr.reshape((3, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
##
np.random.randint(1,10,(3,4,5,12,100))

array([[[[[3, 9, 2, ..., 4, 4, 2],
          [3, 7, 3, ..., 5, 8, 9],
          [2, 2, 3, ..., 7, 4, 6],
          ...,
          [9, 8, 8, ..., 7, 4, 5],
          [1, 3, 9, ..., 5, 9, 7],
          [8, 4, 8, ..., 4, 2, 8]],

         [[6, 6, 8, ..., 2, 2, 8],
          [1, 8, 7, ..., 3, 1, 3],
          [7, 1, 1, ..., 7, 5, 3],
          ...,
          [3, 2, 1, ..., 7, 3, 3],
          [3, 7, 1, ..., 5, 3, 9],
          [7, 6, 9, ..., 3, 7, 5]],

         [[8, 7, 8, ..., 8, 3, 6],
          [4, 4, 3, ..., 6, 6, 6],
          [7, 2, 7, ..., 9, 9, 9],
          ...,
          [7, 9, 6, ..., 6, 1, 6],
          [6, 7, 8, ..., 1, 5, 1],
          [4, 9, 4, ..., 6, 7, 9]],

         [[5, 9, 2, ..., 1, 6, 1],
          [7, 1, 1, ..., 6, 1, 4],
          [9, 5, 8, ..., 9, 3, 9],
          ...,
          [5, 3, 5, ..., 1, 1, 5],
          [9, 5, 6, ..., 1, 7, 9],
          [9, 6, 6, ..., 2, 9, 7]],

         [[3, 5, 2, ..., 3, 3, 1],
          [3, 4, 4, ..., 9, 9, 4],
          [9, 7, 5, ..

In [17]:
np.random.rand(2,2)

array([[0.13773447, 0.1545305 ],
       [0.66825329, 0.41596368]])

In [18]:
np.random.randn(2,3)

array([[-1.45585318,  0.24225028, -1.5513742 ],
       [-0.98869116,  0.84606196,  1.15595666]])

In [21]:
s1 ='Pawan is my Name'
s2 =' I am an Indian'

In [22]:
np.char.add(s1,s2)

array('Pawan is my Name I am an Indian', dtype='<U31')

In [23]:
np.char.upper(s1)

array('PAWAN IS MY NAME', dtype='<U16')

In [24]:
np.char.lower(s1)

array('pawan is my name', dtype='<U16')

In [25]:
np.char.split(s1)

array(list(['Pawan', 'is', 'my', 'Name']), dtype=object)

In [26]:
np.char.splitlines(s1)

array(list(['Pawan is my Name']), dtype=object)

In [27]:
print("hello \n hi")

hello 
 hi


In [28]:
s1="kese ho \nboss"

In [29]:
np.char.splitlines(s1)

array(list(['kese ho ', 'boss']), dtype=object)

In [30]:
np.char.center('good by',80,'*')

array('************************************good by*************************************',
      dtype='<U80')